---
- name: Change network configuration to static IP
  hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: Get default network interface
      set_fact:
        default_interface: "{{ ansible_default_ipv4.interface }}"

    - name: Get IP address from hostname -i
      shell: hostname -i
      register: hostname_ip
      changed_when: false

    - name: Update network configuration
      template:
        src: interfaces.j2
        dest: /etc/network/interfaces
      vars:
        interface: "{{ default_interface }}"
        ip_address: "{{ hostname_ip.stdout }}"

    - name: Restart networking service
      service:
        name: networking
        state: restarted

    - name: Display network configuration change
      debug:
        msg: "Network configuration updated. Interface {{ default_interface }} now has static IP {{ hostname_ip.stdout }}"