version: '3.7'
services:
  llvm-builder-base:
    build:
      context: .
      dockerfile: llvm-builder-base.Dockerfile
      target: llvm-builder-base
    image: ericwf/llvm-builder-base:latest
  llvm-buildbot-worker:
    build:
      context: .
      dockerfile: llvm-buildbot-worker.Dockerfile
      target: llvm-buildbot-worker
    image: ericwf/llvm-buildbot-worker:latest
  llvm-github-actions-worker:
    build:
      context: .
      dockerfile: llvm-github-actions-worker.Dockerfile
      target: llvm-github-actions-worker
      configs:
        - github_runner_token
    configs:
      github_runner_token:
        file: ./secrets/github-token.txt
      my_other_config:
        external: true
    image: ericwf/llvm-github-actions-worker:latest
