version: '3.7'
services:
  llvm-buildbot-worker:
    build:
      context: https://github.com/efcs/llvm-project.git#test:libcxx/utils/docker/debian9/buildbot
      args:
        gcc_tot: "ericwf/gcc:9.2.0"
        llvm_tot: "ericwf/llvm:9.x"
    image: llvm-buildbot-worker
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    secrets:
    - buildbot-auth

secrets:
  buildbot-auth:
    file: buildbot-auth.json
