name: libc++ test

on:
  push:
    branches:
      - self-hosted-runner

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: echo hello
    - name: probe
      run: libcxx/utils/probe.sh
