name: libc++ test

on:
  push:
    branches:
      - github-actions-test

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: efcs/checkout@v2
    - name: configure
      run: |
        mkdir build/
        cd build/
        cmake -GNinja "-DLLVM_ENABLE_PROJECTS=libcxx;libcxxabi" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ../llvm/
    - name: build
      run: |
        cd build/
        ninja cxx cxxabi
    - name: test
      run: |
        cd build
        ./bin/llvm-lit -sv projects/libcxx/test/

