name: libc++ test

on:
  push:

jobs:
  test-basic:
    runs-on: self-hosted
    steps:
    - uses: efcs/checkout@v2
    - uses: ./.github/actions/configure-libcxx
      with:
        cmake_cache: libcxx/utils/test-configurations/Basic.cmake
        build: build-basic
    - uses: ./.github/actions/test-libcxx
      with:
        build: build-basic
        test_suite: libcxx/test/
    - uses: ./github/actions/test-libcxx
      id: test-libcxxabi
      with:
        build: build-basic
        test_suite: libcxxabi/test
