name: libc++ test

on:
  push:

jobs:
  test-basic:
    runs-on: self-hosted
    steps:
    - uses: efcs/checkout@v2
    - name: 'Configure and Build'
      uses: ./.github/actions/configure-and-build-runtimes
    - name: 'Test libc++abi'
      uses: ./.github/actions/test-libcxx
      with:
        test_suite: libcxxabi/test/
    - name: 'Test libc++'
      uses: ./.github/actions/test-libcxx
      with:
        test_suite: libcxxabi/test/
    - name: 'Test C++03'
      uses: ./.github/actions/test-libcxx
      with:
        test_suite: libcxx/test
        lit_args: '--param=std=c++03'
